---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    build_args:
      TTRSS_ORG_VERSION: "${DRONE_TAG##v}"
      TTRSS_VERSION: "${TTRSS_ORG_VERSION%.*}"
    dockerfile: ./Dockerfile.linux.amd64
    dry_run: true
    password:
      from_secret: docker_password
    repo:  xoxys/ttrss
    tags: linux-amd64
    username:
      from_secret: docker_username

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    build_args:
      TTRSS_ORG_VERSION: "${DRONE_TAG##v}"
      TTRSS_VERSION: "${TTRSS_ORG_VERSION%.*}"
    dockerfile: ./Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo:  xoxys/ttrss
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - "refs/tags/**"

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: ./manifest.tmpl
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - "refs/tags/**"

- name: readme
  pull: always
  image: sheogorath/readme-to-dockerhub
  environment:
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPO_NAME: ttrss
    DOCKERHUB_REPO_PREFIX: xoxys
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    README_PATH: README.md
    SHORT_DESCRIPTION: Tiny Tiny RSS - Free and open source news feed reader and aggregator
  when:
    ref:
    - refs/heads/master
    - "refs/tags/**"

- name: microbadger
  pull: always
  image: plugins/webhook
  settings:
    urls:
      from_secret: microbadger_url

- name: matrix
  pull: always
  image: plugins/matrix
  settings:
    homeserver: https://matrix.rknet.org
    password:
      from_secret: matrix_password
    roomid: MtidqQXWWAtQcByBhH:rknet.org
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

trigger:
  status:
  - success
  - failure

depends_on:
- linux-amd64

---
kind: signature
hmac: dc21d353585f6faf703b81baa1265634b52543a981c2745f07859dcc41dcabf7

...
