version: '2.1'

services:
  ttrss:
    image: xoxys/ttrss:latest
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ttrss_plugins:/var/www/app/plugins.local
      - ttrss_icons:/var/www/app/feed-icons
      - ttrss_themes:/var/www/app/themes.local

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure
      POSTGRES_DB: ttrss
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  ttrss_plugins:
    driver: local
  ttrss_icons:
    driver: local
  ttrss_themes:
    driver: local
