version: '2.1'

services:
  ttrss:
    image: xoxys/ttrss:latest
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - plugins:/var/www/app/plugins.local
      - icons:/var/www/app/feed-icons
      - themes:/var/www/app/themes.local
    tmpfs:
      - /var/www/app/cache
      - /var/www/app/lock

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure
      POSTGRES_DB: ttrss
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  plugins:
    driver: local
  icons:
    driver: local
  themes:
    driver: local
